export interface InitialFeature {
  name: string;
  route_path: string;
  module_key: string;
  category: 'auto_shop' | 'powersports' | 'marine' | 'aviation' | 'track_ops';
  is_live: boolean;
  who_can_see: 'public' | 'members' | 'b2b' | 'admin';
  saas_addon_price: number;
  version: string;
  description: string;
  is_saas_module?: boolean;
}

export interface InitialChangelog {
  version: string;
  title: string;
  category: 'feature' | 'bugfix' | 'design' | 'security' | 'refactor';
  description: string;
  timestamp: string;
  author: string;
  route_affected?: string;
}

export const INITIAL_PLATFORM_FEATURES: InitialFeature[] = [
  {
    name: 'Real-Time Telemetry & Session Heatmaps',
    route_path: '/admin/analytics',
    module_key: 'telemetry_engine',
    category: 'track_ops',
    is_live: true,
    who_can_see: 'admin',
    saas_addon_price: 99,
    version: 'v4.2.0',
    description: 'In-house Google Analytics & Microsoft Clarity alternative tracking page views, viewport dimensions, UX rage clicks, and ARR metrics.',
    is_saas_module: true,
  },
  {
    name: 'System Release Control & Changelog HQ',
    route_path: '/admin/changelog',
    module_key: 'changelog_hq',
    category: 'track_ops',
    is_live: true,
    who_can_see: 'admin',
    saas_addon_price: 0,
    version: 'v4.2.0',
    description: 'Centralized live audit panel for system release notes, rule additions, security updates, and bug fixes.',
    is_saas_module: false,
  },
  {
    name: 'Platform Feature & Route Matrix',
    route_path: '/admin/features',
    module_key: 'feature_matrix',
    category: 'track_ops',
    is_live: true,
    who_can_see: 'admin',
    saas_addon_price: 0,
    version: 'v4.1.9',
    description: 'Dynamic registry tracking all Next.js page routes, modular SaaS add-on packages, and access controls.',
    is_saas_module: false,
  },
  {
    name: 'DIY Physical Tag Customizer & Printer',
    route_path: '/build-tag',
    module_key: 'tag_builder',
    category: 'powersports',
    is_live: true,
    who_can_see: 'public',
    saas_addon_price: 29,
    version: 'v4.1.0',
    description: 'Interactive canvas to customize, print, and link QR vinyl decal tags to digital vehicle passports.',
    is_saas_module: true,
  },
  {
    name: 'Driver Garage & Digital Passport HQ',
    route_path: '/dash',
    module_key: 'driver_dash',
    category: 'auto_shop',
    is_live: true,
    who_can_see: 'members',
    saas_addon_price: 0,
    version: 'v4.0.0',
    description: 'Personal garage hub for drivers to manage vehicle specs, service logs, modifications, and business profiles.',
    is_saas_module: false,
  },
  {
    name: 'Universal Search & Directory Explorer',
    route_path: '/explore',
    module_key: 'explore_directory',
    category: 'powersports',
    is_live: true,
    who_can_see: 'public',
    saas_addon_price: 0,
    version: 'v4.0.0',
    description: 'Public discovery directory searching member profiles, verified vehicles, partner dealerships, and venues.',
    is_saas_module: false,
  },
  {
    name: 'Credit & Achievement Leaderboard',
    route_path: '/leaderboard',
    module_key: 'leaderboard',
    category: 'powersports',
    is_live: true,
    who_can_see: 'public',
    saas_addon_price: 0,
    version: 'v4.0.0',
    description: 'Gamification leaderboard displaying driver credit scores, badge achievements, and supporter rankings.',
    is_saas_module: false,
  },
  {
    name: 'Sales CRM & Deal Pipeline Engine',
    route_path: '/admin/crm',
    module_key: 'sales_crm',
    category: 'auto_shop',
    is_live: true,
    who_can_see: 'admin',
    saas_addon_price: 149,
    version: 'v4.1.5',
    description: 'Enterprise B2B deal pipeline tracking merchant proposals, sales staff assignments, and recurring revenue.',
    is_saas_module: true,
  },
  {
    name: 'Geofenced Event Staging Hub',
    route_path: '/events/[id]',
    module_key: 'event_staging',
    category: 'track_ops',
    is_live: true,
    who_can_see: 'public',
    saas_addon_price: 79,
    version: 'v4.1.0',
    description: 'Live event staging grid showing driver entry manifests, tech inspection statuses, and sponsor logos.',
    is_saas_module: true,
  },
  {
    name: 'Second Life Sim & Club Management SaaS',
    route_path: '/secondlife',
    module_key: 'secondlife_saas',
    category: 'track_ops',
    is_live: true,
    who_can_see: 'public',
    saas_addon_price: 49,
    version: 'v4.3.0',
    description: 'In-world Second Life prim touch SSO avatar authentication, live region telemetry, visitor tracking, and digital passports.',
    is_saas_module: true,
  },
];

export const INITIAL_PLATFORM_CHANGELOGS: InitialChangelog[] = [
  {
    version: 'v4.7.0',
    title: 'Immutable Subcollection Telemetry Architecture, Hall of Fame Leaderboard & Jargon-Free Analytics',
    category: 'feature',
    description: 'Upgraded Second Life Telemetry to write immutable standalone log documents to sl_venues/{slug}/telemetry_logs subcollection on every ping, implemented Top Residents & Time in Sim Hall of Fame Leaderboard with Gold/Silver/Bronze podium cards, exact timestamp delta calculations, and complete jargon removal across all views.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.6.0',
    title: 'Advanced Second Life Venue Traffic Analytics, Event Audit Stream & Multi-Prim Beacon Station Manager',
    category: 'feature',
    description: 'Upgraded Second Life Venue Portal with 24-Hour SLT Avatar Density Distribution Bar Charts, Resident Loyalty Ratio % metrics, Dynamic Prim & Parcel Spatial Zones, Avatar Activity & Event Audit Stream HQ (/secondlife/[slug]?tab=logs), Active vs Inactive Prim Beacon Partitioning, 1-Click Prim Unregistering, and layperson-friendly terminology across all venue tools.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.5.0',
    title: 'Second Life Venue Portal & Telemetry Engine Upgrades (v4.6 LSL Bridge, Master Test Shield, Staff Group Auto-Exclusion & Admin Route)',
    category: 'feature',
    description: 'Upgraded Second Life Venue Portal with dynamic /secondlife/[slug]?tab=admin route, 1-click Master In-World Test Mode safety shield (restricting all rules IMs strictly to PJ Losey during testing), Staff & Group Tag (OBJECT_GROUP & 77be7a67-1b4d-14b6-8cd3-baa441886f41) auto-exclusion (preventing staff spam), and LSL v4.6 auto-renaming prims to [Sim Name] | GridPass.app - Message with clean ASCII character formatting.',
    timestamp: '2026-08-05T20:55:00.000Z',
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.3.0',
    title: 'Second Life Sim Rules Governance, Live DJ Music Editor & Passive Notecard Auto-Delivery Engine (LSL v3.7)',
    category: 'feature',
    description: 'Deploys dynamic Sim Rules Governance tab (/secondlife/[slug]?tab=rules) with versioning (v1.0, v2.0), rule publishing, and resident Notecard compliance tracking. Upgraded Second Life Prim Bridge script to v3.7 with DJ "Now playing:" chat capture, live audio stream override, and passive automatic in-world Notecard delivery upon sim arrival.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.2.4',
    title: 'Second Life Sim Destination Engine v3.4, First-Party Map Proxy & Public Analytics',
    category: 'feature',
    description: 'Upgraded LSL Bridge to v3.4 Zero-Config Auto-Slug Edition with llGetRegionCorner() tile positioning, added first-party Second Life map proxy (/api/secondlife/map-proxy) bypassing browser tracking protection, enabled public Sim Analytics HQ, auto-collapsing hero banner, and fixed offline resident status timestamps.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.2.10',
    title: 'Second Life Sim & Club Management SaaS & In-World Prim Touch SSO',
    category: 'feature',
    description: 'Expanded Gridpass to Second Life with a dedicated Sim & Club Management SaaS portal under /secondlife/[slug]. Features in-world prim touch SSO authentication (grabbing slKey, legacyName, displayName, region, parcel), automated avatar account creation in live database with 100 default starting credits, live region telemetry, and LSL Mono bridge script generator.',
    timestamp: '2026-08-04T20:40:00Z',
    author: 'antigravity',
    route_affected: '/secondlife/[slug]',
  },
  {
    version: 'v4.6.0',
    title: 'Physical QR Decal Intake Engine, 1-Tap Google OAuth Registration & Unclaimed Machine/Business Passport Claiming Studio',
    category: 'feature',
    description: 'Released full physical QR decal intake engine on /join. Features 1-Tap Google OAuth popup sign-in, dynamic business passport hero cards (/join?id=monarch-defender), business photo staging, 1-tap unclaimed asset transfer & auto-redirect to profile, interactive VIP share link generator studio, unclaimed vehicle passport claim banners on /v/[id], City/Region & personal note dual-collection persistence, and Apple-native mobile touch target & iOS auto-zoom prevention upgrades.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/join, /v/[id], /b/[id], /admin/tickets',
  },
  {
    version: 'v4.2.7',
    title: 'High-Density Event Grid Roster & Inline Entrant/Vendor/Guest Views',
    category: 'feature',
    description: 'Re-architected Event Grid tab into a 3-way segmented control (Vehicles, Vendors, People) with high-density compact horizontal rows (64x48 photo thumbnail, title, engine specs/location, and action pills). Built inline Entrant, Vendor, and Guest detail views with top ← Back to Grid button, keeping users fully immersed on the event page. Fixed QR code deep links (?entrant=...) to directly open the vehicle entry view with 🔥 Respect & Upvote voting.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.4.1',
    title: 'Integrated Complete Full Event Host Editor & Reschedule Suite (/events/[id]/edit)',
    category: 'feature',
    description: 'Routed Edit Event & Edit Event Details action buttons directly to the comprehensive standalone event editor suite (/events/[id]/edit). Includes event weather rescheduling alerts, original vs new date pickers, registration permission toggles (vehicles, spectators, vendor booths), entry fees, safety waivers, tech inspection requirements, staging vehicle class filters, interactive GPS pin maps & high-res cover banner uploads.',
    timestamp: '2026-08-02T22:48:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]/edit',
  },
  {
    version: 'v4.4.0',
    title: 'Inline Page Entrant & Business Spotlights, 48h Event Archive Filter, Print Gridpass Renaming & Anti-Abuse Deduplication',
    category: 'feature',
    description: 'Upgraded event entrant cards under /events/[id] to expand inline directly on the page (zero popup modals) with full build photos, Lightbox zoom, 1-tap respect upvotes, and direct action links. Added 48-hour active vs archive event filter to /explore directory with automatic post-event grace window. Renamed all pass export buttons to Print Gridpass. Integrated toast stack capping and per-build respect upvote deduplication.',
    timestamp: '2026-08-02T22:28:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id], /explore',
  },
  {
    version: 'v4.3.0',
    title: 'Live Event Discussion Hub with Native Camera Uploads, Lightbox, Inline Facebook Replies, Pinned Bulletins & Auto-Moderation',
    category: 'feature',
    description: 'Released full real-time event discussion ecosystem on /events/[id]. Features native mobile camera/photo attachments, full-screen Lightbox zoom viewer, always-visible inline Facebook-style reply threads, 4 automotive quick reactions (Respect, Love, Grid, Bravo), host/admin pinned bulletins & comment pinning, auto-archiving for reported content (3+ reports), and 1-tap moderator post restoration.',
    timestamp: '2026-08-02T21:15:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.3.0',
    title: 'Restored Official Original Gridpass Logo Emblem Across Site & QR Generators',
    category: 'design',
    description: 'Saved high-res original Gridpass logo asset (public/gridpass_logo.png) and created 1:1 vector geometry featuring silver mountain peaks, red-and-white rumble curbs, and sweeping crimson track line across Logo.tsx, GridpassQRCode.tsx, opengraph-image.tsx, and favicon icon files.',
    timestamp: '2026-08-02T11:31:00.000Z',
    author: 'antigravity',
    route_affected: 'Site-Wide',
  },
  {
    version: 'v4.2.9',
    title: 'Printable 8.5x11 Event Windshield Display Pass & QR Referral Exporter',
    category: 'feature',
    description: 'Added high-res 8.5x11 printable display pass modal with print CSS isolation (@media print) for staged builds and vendor booths. Integrated custom Gridpass logo QR codes and automated member referral links (/join?ref=code) granting +100 bonus Pit Credits.',
    timestamp: '2026-08-02T10:07:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.8',
    title: 'Interactive Event Radar Map, Venue Directions & Spot Pinning Expansion',
    category: 'feature',
    description: 'Added 1-tap turn-by-turn system map directions (Apple Maps on iOS/Mac, Google Maps on Web/Android), spot position locks, and amenity pin categories (Restrooms 🚻, Water 💧, Food 🍔, Parking 🅿️, First Aid 🚑, Info ℹ️).',
    timestamp: '2026-08-02T09:40:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.7',
    title: 'Universal 1-Tap Calendar Exporters (.ICS, Google, Outlook, Yahoo)',
    category: 'feature',
    description: 'Built universal calendar export suite featuring direct .ics file generation for Apple iCal, iPhone, Mac, and Outlook, alongside web deep links for Google Calendar and Yahoo.',
    timestamp: '2026-08-02T09:20:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.6',
    title: 'Test Account Database Purge & Leaderboard Production Isolation',
    category: 'security',
    description: 'Purged test entries (e.g. Sarah Sales Rep) from live Firestore collections using db-inspect.mjs and added production test user filter on /leaderboard to isolate GPTestUser_* accounts.',
    timestamp: '2026-08-02T09:00:00.000Z',
    author: 'antigravity',
    route_affected: '/leaderboard',
  },
  {
    version: 'v4.2.5',
    title: 'Updated Platform Positioning & Metadata to "One Tag for Everything"',
    category: 'design',
    description: 'Replaced legacy "The Universal Vehicle Network" tagline across metadata, manifest, OpenGraph cards, and AGENTS.md with "Gridpass | One Tag for Everything" and the tagline: "Whether you race it, show it, cook it, or capture it — Gridpass brings your world together."',
    timestamp: '2026-08-02T10:06:00.000Z',
    author: 'antigravity',
    route_affected: '/',
  },
  {
    version: 'v4.2.4',
    title: 'Replaced Default Vercel Favicon with Custom Gridpass Brand Logo & Apple Touch Icons',
    category: 'design',
    description: 'Removed default Vercel triangle favicon.ico and implemented dynamic Next.js icon generators (src/app/icon.tsx & src/app/apple-icon.tsx) featuring the official Gridpass mountain peak and Crimson #ff3b30 racetrack stripe logo.',
    timestamp: '2026-08-02T10:04:00.000Z',
    author: 'antigravity',
    route_affected: '/',
  },
  {
    version: 'v4.2.3',
    title: 'Refactored Overly Specific "Crew" Terminology to Inclusive "Attendee / Guest" Labels',
    category: 'refactor',
    description: 'Replaced race-team specific "Crew" labels in radar location pin modals, share buttons, and event hub feeds with general "Attendee", "Invite Friends", and "Attending Guests & Spectators" terminology.',
    timestamp: '2026-08-02T08:11:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.2',
    title: 'Codified Rule 17 (Universal Polymorphic Event & Venue Scope Invariant)',
    category: 'design',
    description: 'Updated event creation dropdowns, venue profiles, and event hubs to use broad, inclusive terminology (One-Time Event / Gathering, Permanent Venue / Destination) to natively support car shows, food truck pop-ups, cruise nights, jet-ski meets, and offroad parks alongside motorsport racing.',
    timestamp: '2026-08-02T07:58:00.000Z',
    author: 'antigravity',
    route_affected: '/events/create',
  },
  {
    version: 'v4.3.1',
    title: 'Removed Redundant View Selector Pills & Streamlined Entrants Grid',
    category: 'design',
    description: 'Removed redundant "All Entrants / Vehicles Only / Vendors" filter pill bar to eliminate top-of-page clutter and maximize vertical content space on mobile viewports.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.3.0',
    title: 'Persistent Build Upvoting System & Attending Exhibitors Terminology',
    category: 'bugfix',
    description: 'Fixed Build Upvote persistence by writing vote counters to Firestore (entrants.{id}.votes) and syncing to localStorage (gp_upvoted_builds_{id}). Updated vendor section banner heading to "Attending Exhibitors & Vendors" for authentic community representation.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.9',
    title: 'Custom Viral Share & Collect Votes Modal & Address Bar URL Protection',
    category: 'feature',
    description: 'Built a high-converting Gridpass Share & Collect Votes Modal. Fixed address bar pasting by separating clean URL copying (Copy Direct Voting Link) from promotional social captions (SMS, WhatsApp, X, Facebook, Copy Full Caption) and adding an in-person screen QR code.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.8',
    title: 'Automated Smooth Auto-Scroll to Scanned Vehicle / Vendor Card',
    category: 'feature',
    description: 'Added smooth auto-scrolling (scrollIntoView center) to immediately bring the scanned vehicle build or vendor exhibitor card directly into view when spectators scan a physical windshield QR pass.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.7',
    title: 'Printable Pass QR Deep Linking to Entrants Tab & Vehicle Spotlight',
    category: 'bugfix',
    description: 'Updated Printable Display Pass QR code URLs to include tab=entrants&entrant={id}. Updated Event Hub route handler to automatically switch to the Entrants tab and open/expand the scanned vehicle or vendor passport card when scanned by spectators.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.6',
    title: 'Dynamic Racing Flag Lifecycle Engine & Sub-Tab Quick-Join Bar',
    category: 'feature',
    description: 'Added Dynamic Racing Flag Engine to Event Radar map pin (Green Flag 🟩 before event/live -> White Flag 🏳️ in final 45 mins -> Checkered Flag 🏁 when completed). Integrated a 28px Quick-Join action bar (+ Join Vehicle | + Join Vendor) directly inside the sticky top header on all sub-tabs (MAP, PASSES, GRID, CHAT) so drivers and vendors can register in 1 tap without navigating back to HUB.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.5',
    title: 'Zero Vertical Overhead Sub-Tab Views & AppShell Header Cleanup',
    category: 'design',
    description: 'Suppressed duplicate global AppShell top header on event hub pages. Conditioned Cover Image and Master Header Card to render ONLY on HUB tab view. Sub-tabs (MAP, PASSES, GRID, CHAT) now start immediately below the sticky top header bar, giving 100% full-screen dedicated viewports across all mobile devices.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.4',
    title: 'Ultra-Compact Master Event Header & Vertical Space Elimination',
    category: 'design',
    description: 'Consolidated Card 1 (Title/Badges/Location) and Card 2 (RSVP/Actions/Join Buttons) into a single high-density master card. Replaced stacked full-width Join buttons with a side-by-side 2-column grid (+ Join Vehicle | + Join Vendor). Reduced cover image height on mobile (h-28 sm:h-36) and removed duplicate overlay headers, saving 250px+ of vertical space above the fold.',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.3',
    title: 'Event Hub Mobile UI/UX Optimization & Top Floating Header Deck',
    category: 'design',
    description: 'Unified top topbar and event navigation bar into a sticky floating header deck. Compacted tab bar to fit standard mobile viewports (~360px-425px) without horizontal clipping. Streamlined Map area action buttons and filter pills. Reduced My Passes card inner padding and made action buttons compact wrap rows. Added Top Featured Exhibitors Showcase strip and Entrant View selector (All vs Vehicles vs Vendors).',
    timestamp: new Date().toISOString(),
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.2',
    title: 'Real-Time Firestore Sync & Persistence Fix for Event Hub',
    category: 'bugfix',
    description: 'Fixed isMockEventId to allow real Firestore reads/writes for events like maple-city-cruise. Auto-seeded event document to Firestore and synced cover_url, banner_url, and registered vehicle entrants live across all devices.',
    timestamp: '2026-08-02T17:55:00.000Z',
    author: 'antigravity',
    route_affected: '/events/[id]',
  },
  {
    version: 'v4.2.1',
    title: 'Codified Rule 14 (Live Database Inspection) & Rule 15 (Process Cleanup)',
    category: 'security',
    description: 'Codified Rule 14 requiring live database inspection via /admin/db or CLI inspector (db-inspect.mjs) before diagnosing errors, and Rule 15 enforcing immediate process cleanup for test runner tasks.',
    timestamp: '2026-08-02T07:06:00.000Z',
    author: 'antigravity',
    route_affected: '/admin/db',
  },
  {
    version: 'v4.2.0',
    title: 'Integrated In-House Google Analytics & Microsoft Clarity Telemetry Engine',
    category: 'feature',
    description: 'Deploys first-party GridpassTelemetryProvider to log route page views, viewport dimensions, click streams, 25%/50%/75%/100% scroll depth, and UX rage clicks. Added Localhost traffic suppression filter and real-time active user map.',
    timestamp: '2026-08-02T06:45:00.000Z',
    author: 'antigravity',
    route_affected: '/admin/analytics',
  },
  {
    version: 'v4.1.9',
    title: 'Deployed Admin System Release & Changelog Audit Control Panel',
    category: 'feature',
    description: 'Created /admin/changelog HQ connected via onSnapshot real-time listeners to Firestore. Enforces Rule 12 requiring every architectural refactor and feature deployment to be audited.',
    timestamp: '2026-08-02T06:40:00.000Z',
    author: 'antigravity',
    route_affected: '/admin/changelog',
  },
  {
    version: 'v4.1.8',
    title: 'Site-Wide Terminology Invariant Refactor ("Register" -> "Join")',
    category: 'refactor',
    description: 'Refactored user-facing text across /build-tag, /dash, /events/[id], /members, and /vehicles from "Register" to "Join", "Add", "Claim", or "Verified" to match physical print materials.',
    timestamp: '2026-08-02T06:47:00.000Z',
    author: 'antigravity',
    route_affected: 'Site-Wide',
  },
  {
    version: 'v4.1.5',
    title: 'Enterprise B2B Sales CRM & Deal Pipeline Deployment',
    category: 'feature',
    description: 'Built multi-stage Kanban CRM deal tracking (/admin/crm) with sales staff assignments, revenue forecasting, and product package attachments.',
    timestamp: '2026-08-01T18:30:00.000Z',
    author: 'antigravity',
    route_affected: '/admin/crm',
  },
  {
    version: 'v4.1.0',
    title: 'DIY Physical Tag Customizer & Printer Rollout',
    category: 'feature',
    description: 'Launched interactive tag customizer (/build-tag) allowing drivers to design custom QR vinyl decals, select accent colors, print Avery templates, and link digital garage passports.',
    timestamp: '2026-07-30T12:00:00.000Z',
    author: 'antigravity',
    route_affected: '/build-tag',
  },
  {
    version: 'v4.0.0',
    title: 'Gridpass Platform Core Architecture Release',
    category: 'feature',
    description: 'Initial deployment of Gridpass-v4 core framework including Next.js App Router, Tailwind design system, Firestore rules sync, and Apple native mobile viewport optimizations.',
    timestamp: '2026-07-25T00:00:00.000Z',
    author: 'antigravity',
    route_affected: 'Core System',
  },
];
