import { createClient } from '@supabase/supabase-js';
import { NextRequest, NextResponse } from 'next/server';

// Initialize Supabase Admin client
const supabase = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
);

export async function POST(req: NextRequest) {
    try {
        const { entityType, entityId, email } = await req.json();

        if (!entityType || !entityId) {
            return NextResponse.json({ error: 'Missing entityType or entityId' }, { status: 400 });
        }

        if (!['lead', 'job'].includes(entityType)) {
            return NextResponse.json({ error: 'Invalid entityType' }, { status: 400 });
        }

        // 1. Check if token already exists
        const { data: existing } = await supabase
            .from('claim_tokens')
            .select('token')
            .eq('entity_type', entityType)
            .eq('entity_id', entityId)
            .maybeSingle();

        if (existing) {
            return NextResponse.json({
                token: existing.token,
                link: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://www.gridpass.app'}/claim/${existing.token}`
            });
        }

        // 2. Create new token
        // Token is generated by default in DB, or we can generate here.
        // Let's rely on DB default if we didn't pass one, but we need to fetch it back.
        // Actually, let's generate a random hex here to be safe and return it immediately.
        const token = Array.from(crypto.getRandomValues(new Uint8Array(16)))
            .map(b => b.toString(16).padStart(2, '0')).join('');

        const { error } = await supabase
            .from('claim_tokens')
            .insert({
                entity_type: entityType,
                entity_id: entityId,
                email: email || null,
                token: token
            });

        if (error) throw error;

        return NextResponse.json({
            token: token,
            link: `${process.env.NEXT_PUBLIC_SITE_URL || 'https://www.gridpass.app'}/claim/${token}`
        });

    } catch (error: any) {
        console.error('Error generating invite:', error);
        return NextResponse.json({ error: error.message }, { status: 500 });
    }
}
